# Beginner's Lesson

 ## First Lesson

Most of this involves getting acquainted with numpy which will be used later on for math operations. Also understanding some basic python functions. Pretty helpful phase :)

In [1]:
import numpy
import sklearn

In [2]:
sklearn.__version__

'0.22.1'

In [3]:
numpy.linspace(1,100,100)


array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [4]:
firstarray = numpy.linspace(1,100,100)

In [5]:
firstarray

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [6]:
firstarray+1

array([  2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
        13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,
        24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,
        35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,
        46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,
        57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,
        68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,
        79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,
        90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.,
       101.])

In [7]:
firstarray

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [8]:
firstarray=([  2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
        13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,
        24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,
        35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,
        46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,
        57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,
        68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,
        79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,
        90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.,
       101.])


In [9]:
# this wont work bcos you can't do such addition with a list you'd need to convert to numpy array
#firstarray+1

In [10]:
numbr = range(10,20)

In [11]:
print(numbr)

range(10, 20)


In [12]:
print(numbr[1])

11


In [13]:
print(numbr)

range(10, 20)


In [14]:
count=0
newnumbr = []
while count<len(numbr):
    print(numbr[count])
    newnumbr.append(numbr[count])
    count+=1
    print(count)

10
1
11
2
12
3
13
4
14
5
15
6
16
7
17
8
18
9
19
10


In [15]:
len(numbr)

10

In [16]:
print(newnumbr)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [17]:
letters = "my name is Mark"
count = 0
while True: 
    newletter = letters.split(" ")
    print(newletter[count])
    count +=1
    if count == len(newletter):
        break
    

my
name
is
Mark


In [18]:
len(newletter)

4

In [19]:
adele = "Hello the  other side" + " I must have called a thousand times"
print(adele)

Hello the  other side I must have called a thousand times


# Adele's Cell

In [20]:
def LauriBlue(count):
        adele = "Hello from the other side" + " I must have called a thousand times"
        hello = adele.split(" ")
        print(hello[count])
        return hello
    
count = 0
hello=LauriBlue(3)
while True:
    if count == len(hello):
        break
    LauriBlue(count)
    count += 1
    


other
Hello
from
the
other
side
I
must
have
called
a
thousand
times


In [21]:
empt =[]
if not empt:
    print('2')

2


In [22]:
LauriBlue(1)

from


['Hello',
 'from',
 'the',
 'other',
 'side',
 'I',
 'must',
 'have',
 'called',
 'a',
 'thousand',
 'times']